#!/bin/sh -x

# Get the defaults
. ./pivertise.conf

HCICONFIG=`which hciconfig`
HCITOOL=`which hcitool`

# Start LE advertising
echo "Launching pivertise..."
sudo $HCICONFIG $BLUETOOTH_DEVICE up
sleep .1
sudo $HCICONFIG $BLUETOOTH_DEVICE name $NAME
sleep .1
sudo $HCICONFIG $BLUETOOTH_DEVICE noleadv
sleep .1
sudo $HCICONFIG $BLUETOOTH_DEVICE noscan
sleep .1
sudo $HCICONFIG $BLUETOOTH_DEVICE leadv 3
sleep .1
sudo $HCITOOL -i $BLUETOOTH_DEVICE cmd 0x08 0x0008 1e 02 01 1a 1a ff 4c 00 02 15 $UUID $MAJOR $MINOR $POWER

echo "Complete"
exit 0
